### ISSUE TITLE
Incorrect behaviour for zero length arrays

### ISSUE THREAD

**Issue by jeromekelleher** [alimanfoo/zarr#187]
```python
>>> import numpy as np
>>> a = np.zeros((0,))
>>> a
array([], dtype=float64)
>>> a.shape
(0,)
>>> a[:] = a
>>> z = zarr.array((0,))
>>> z
Array((1,), int64, chunks=(1,), order=C)
  nbytes: 8; nbytes_stored: 311; ratio: 0.0; initialized: 1/1
  compressor: Blosc(cname='lz4', clevel=5, shuffle=1)
  store: dict
>>> z.shape
(1,)
>>> z[:] = a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jk/.local/lib/python3.4/site-packages/zarr/core.py", line 582, in __setitem__
    str(value.shape)))
ValueError: value has wrong shape, expecting (1,), found (0,)
```

Note the difference between the behaviour for numpy arrays and zarr arrays. It seems that the issue is that the shape gets changed from 0 to 1 in the zarr array?

**Comment by alimanfoo** [comment]
This should be fixed in master, xref #150, #160.

**Comment by jeromekelleher** [comment]
Awesome, thanks @alimanfoo!

**Comment by alimanfoo** [comment]
No probs.
